// <auto-generated />
using System;
using ITAMS_GME_BACKEND.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAMS_GME_BACKEND.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622140106_SecondAuth")]
    partial class SecondAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Action")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Create",
                            Module = "Users"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Read",
                            Module = "Users"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Update",
                            Module = "Users"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Delete",
                            Module = "Users"
                        },
                        new
                        {
                            Id = 5,
                            Action = "Create",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = 6,
                            Action = "Read",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = 7,
                            Action = "Update",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = 8,
                            Action = "Delete",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Create",
                            Module = "Categories"
                        },
                        new
                        {
                            Id = 10,
                            Action = "Read",
                            Module = "Categories"
                        },
                        new
                        {
                            Id = 11,
                            Action = "Update",
                            Module = "Categories"
                        },
                        new
                        {
                            Id = 12,
                            Action = "Delete",
                            Module = "Categories"
                        },
                        new
                        {
                            Id = 13,
                            Action = "Create",
                            Module = "Maintenance"
                        },
                        new
                        {
                            Id = 14,
                            Action = "Read",
                            Module = "Maintenance"
                        },
                        new
                        {
                            Id = 15,
                            Action = "Update",
                            Module = "Maintenance"
                        },
                        new
                        {
                            Id = 16,
                            Action = "Delete",
                            Module = "Maintenance"
                        },
                        new
                        {
                            Id = 17,
                            Action = "Read",
                            Module = "AuditLogs"
                        },
                        new
                        {
                            Id = 18,
                            Action = "Read",
                            Module = "Notifications"
                        });
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            Name = "IT Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            Name = "IT Staff"
                        });
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrantedBy")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.User", b =>
                {
                    b.HasOne("ITAMS_GME_BACKEND.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.UserPermission", b =>
                {
                    b.HasOne("ITAMS_GME_BACKEND.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAMS_GME_BACKEND.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITAMS_GME_BACKEND.Models.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
