name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 — SSH into VM and deploy, docker image prune -f will remove dangling images to free up space, -f will force the prune without confirmation
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/itams/ITAMS
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            docker image prune -f
